server:
  port: 8081

spring:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/user_details
      username: root
      password: sahil12
  jpa:
    mysql:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

sqlite_db:
  datasource:
    sqlite:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:session.db
  jpa:
    sqlite:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.community.dialect.SQLiteDialect

file-storage:
  container1:
    host: comp20081-files-container1
    port: 22
  container2:
    host: comp20081-files-container2
    port: 22
  container3:
    host: comp20081-files-container3
    port: 22
  container4:
    host: comp20081-files-container4
    port: 22
  ssh:
    username: ntu-user
    private-key-path: ${user.home}/.ssh/id_ed25519
    public-key-path: ${user.home}/.ssh/id_ed25519.pub
